### ISSUE TITLE
App details

### ISSUE THREAD

**Issue by Rishi117** [Druhin13/corona#16]
The app shows statistics of India. But its nowhere written in the app. If possible, add a graph. Graphical representations attract more people. Or if sourcrs are available, try to add state wise data also. The app is accurate and smooth and pretty helpful.

**Comment by Druhin13** [comment]
India 🇮🇳 added in the top-bar

**Comment by Druhin13** [comment]
Not sure, if the state wise data can be added or not

**Comment by Druhin13** [comment]
State data added

**Comment by Druhin13** [comment]
Graph added for - Daily cases in India

**Comment by Druhin13** [comment]
Graph added for - Patient Age in India
