### ISSUE TITLE
graphs for states

### ISSUE THREAD

**Issue by Archis03007** [Druhin13/corona#24]
**Is your feature request related to a problem? Please describe.**
not really a problem, a feature which is more helpful

**Describe the solution you'd like**
add graphs of cases, deaths and recovered for states.

**Describe alternatives you've considered**

**Additional context**
make the animations a bit faster if you can ( not a problem, just a suggestion)

**Comment by PuranjanT** [comment]
@Archis03007 Not sure about the animations, but I hope state data can be added

**Comment by new-captha** [comment]
@PuranjanT agreed

@Archis03007 animations are ok. users's own state data is already added.
hopefully @Druhin13 will also add the other state's data

**Comment by Druhin13** [comment]
@Archis03007 Ya, the thing is that, the animations are used to take down the time used to load the data from the database. So for now, let's keep it that way

@PuranjanT @new-captha

**Comment by Druhin13** [comment]
@new-captha and yes, all the state's data will be added soon (in the upcoming release)
it's halfway done
@Archis03007

**Comment by Druhin13** [comment]
State graphs will be added in the 'Live State Statistics' page
<Graphs> button will be added

**Comment by ad-dr** [comment]
@Archis03007  I don't see the proper need of this

**Comment by ad-dr** [comment]
@Druhin13 prioritize the issues
I think, live news is more needed

**Comment by d10-10** [comment]
> @Archis03007 I don't see the proper need of this

agreed !!
