### ISSUE TITLE
Recent updates or news

### ISSUE THREAD

**Issue by PuranjanT** [Druhin13/corona#25]
**Is your feature request related to a problem? Please describe.**
It’s a feature request for showing recent news or updates 

**Describe the solution you'd like**
Recent updates or news about a particular state (eg: recent 2 deaths in West Bengal)

**Describe alternatives you've considered**
Set a page for recent updates, or place it anywhere in the homepage itself 

**Additional context**
The app is working flawless. Thanks

**Comment by new-captha** [comment]
@PuranjanT maybe homepage is a better place, than creating a whole separate page for the news/updates.

@Druhin13 what you say ?

**Comment by ad-dr** [comment]
@PuranjanT I think this is a much needed feature
@Druhin13

**Comment by Druhin13** [comment]
@ad-dr working on it. will be there in the next release

**Comment by Druhin13** [comment]
Added in Release 3.0
